[package]
name = "feature-scope"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }

proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
