[package]
name = "feature-scope"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
_macros = { path = "../feature-scope-macros", package = "feature-scope-macros", version = "0.1.0" }

anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
cargo-lock = { workspace = true }
