[package]
name = "feature-scope-macros"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }

syn = { version = "^2", features = ["full"] }
proc-macro2 = "^1"
quote = "^1"
