name: Clippy

on:
  pull_request:
    paths:
      - '.github/workflows/clippy.yml'
      - 'packages/**/*'
      - 'examples/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [main]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-feature-scope
        run: cargo install --path packages/cli

      - name: Run clippy
        run: |
          cargo clippy \
            --all-targets \
            --all-features \
            --workspace \
            -- -D warnings

      - name: Run clippy on examples with cargo-feature-scope
        run: |
          cd examples/basic_workspace
          cargo feature-scope build
          # Run clippy on each example package
          cargo feature-scope clippy
