name: Test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'packages/**/*'
      - 'examples/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [main]

jobs:
  clippy:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Install cargo-feature-scope
        run: cargo install --path packages/cli

      - name: Run unit test
        run: |
          cargo test \
            --all-targets \
            --all-features \
            --workspace \
            --no-fail-fast

      - name: Test examples with cargo-make
        run: cargo make test-examples
